# Generated by Django 5.2.4 on 2025-11-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
