# Generated by Django 5.2.4 on 2025-11-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_bill_bill_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='packing_charge',
        ),
        migrations.AddField(
            model_name='bill',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
