# Generated by Django 5.2.4 on 2025-11-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_remove_bill_packing_charge_bill_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='extra_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='extra_label',
            field=models.CharField(blank=True, default='Packing', max_length=50, null=True),
        ),
    ]
