# Generated by Django 5.2.4 on 2025-11-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_bill_extra_amount_bill_extra_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='extra_amount',
            new_name='packing_charge',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='extra_label',
        ),
    ]
