# Generated by Django 5.2.4 on 2025-11-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_rename_extra_amount_bill_packing_charge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='packing_charge',
            new_name='extra_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='extra_label',
            field=models.CharField(blank=True, default='Packing', max_length=50, null=True),
        ),
    ]
