# Generated by Django 5.2.4 on 2025-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_rename_extra_amount_bill_packing_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
