# Generated by Django 5.2.4 on 2025-11-09 16:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_bill_rate_alter_billitem_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
        migrations.AlterField(
            model_name='bill',
            name='packing_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10),
        ),
    ]
