# Generated by Django 5.2.4 on 2025-11-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_bill_paid_amount_alter_bill_packing_charge_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date', '-bill_no'], 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
