# Generated by Django 5.2.4 on 2025-11-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_alter_bill_options_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='extra_reason',
            field=models.CharField(blank=True, help_text='Reason for extra charge (e.g. Packing, Service, Discount)', max_length=255, null=True),
        ),
    ]
