# Generated by Django 5.2.4 on 2025-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_bill_extra_amount_bill_packing_qty_bill_packing_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
