# Generated by Django 5.2.4 on 2025-11-22 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_bill_packing_reason_alter_bill_bill_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='archived',
            field=models.BooleanField(default=False, help_text='Soft-archived (e.g. hide after X days)'),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
