# Generated by Django 5.2.4 on 2025-11-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_billreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
