# Generated by Django 5.2.4 on 2025-11-25 16:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0022_alter_billitem_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billreturn',
            options={'ordering': ['-date'], 'verbose_name': 'Bill Return', 'verbose_name_plural': 'Bill Returns'},
        ),
        migrations.AddField(
            model_name='bill',
            name='returned_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
