# Generated by Django 5.2.4 on 2025-11-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0023_alter_billreturn_options_bill_returned_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
