# Generated by Django 5.2.4 on 2025-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0024_alter_bill_archived_alter_bill_customer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date', '-bill_no']},
        ),
        migrations.AlterModelOptions(
            name='billreturn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='packing_charge',
        ),
        migrations.RemoveField(
            model_name='billreturn',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
