# Generated by Django 5.2.4 on 2025-11-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0025_alter_bill_options_alter_billreturn_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='code',
        ),
    ]
