# Generated by Django 5.2.4 on 2025-12-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0026_remove_billitem_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_start', models.CharField(max_length=10)),
                ('financial_year_end', models.CharField(max_length=10)),
                ('lock_date', models.CharField(max_length=10)),
                ('system_date', models.CharField(max_length=10)),
            ],
        ),
    ]
